cors:
  originPatterns: http://localhost:8080,http://localhost:3000,https://brunotrindade.dev

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/rest_with_spring_boot
    username: postgres
    password: admin

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

spring-doc:
  paths-to-match:
    - /api/v1/**
  swagger-ui:
    use-root-path: true
